name: docs-build

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docs
        uses: michalbundyra/documentation-theme/github-actions/docs@feature/checkout-repo
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
